package com.lukasbeckercode.forrestwatch.models

import android.content.res.Resources
import android.os.Parcel
import android.os.Parcelable
import android.text.TextUtils
import com.lukasbeckercode.forrestwatch.R

/**
 * Class representing a User
 * @param id unique user id (generated by Firebase auth)
 * @param email email used to register and sign in, also used for resetting password
 * @param firstname a users first name
 * @param lastname a users last name
 *
 * Implements Parcelable Interface so users can be passed on between Activities using intents
 */
class User(
    var id: String? ="",
    var email: String? ="",
    var firstname: String? ="",
    var lastname: String?=""

):Parcelable {

    constructor(parcel: Parcel) : this(
        parcel.readString(),
        parcel.readString(),
        parcel.readString(),
        parcel.readString()
    )

    constructor() : this(
        id="",
        email ="",
        firstname ="",
        lastname=""
    )

    /**
     * Validates email address and checks if passwords match
     * @param passwd first entered password
     * @param confirmPasswd second entered password. should match passwd
     */
    fun validate(passwd:String, confirmPasswd:String): Boolean {
        email = email!!.trim()
        firstname = firstname!!.trim()
        lastname = lastname!!.trim()
        when{
            TextUtils.isEmpty(email) -> throw IllegalArgumentException(Resources.getSystem().getString(R.string.error_empty_email))
            TextUtils.isEmpty(firstname) -> throw IllegalArgumentException(Resources.getSystem().getString(R.string.error_empty_firstname))
            TextUtils.isEmpty(lastname) -> throw IllegalArgumentException(Resources.getSystem().getString(R.string.error_empty_lastname))
        }
        when{
             passwd.trim() != confirmPasswd.trim() -> return false
             !email!!.contains('@') -> return false
         }
  return true
    }

    /**
     * empties current user object, used to secure sign out
     */
    fun destroy(){
        id = ""
        firstname = ""
        lastname = ""
        email = ""

    }
//----------implementation of Parcelable Interface-----------
    override fun writeToParcel(parcel: Parcel, flags: Int) {
        parcel.writeString(id)
        parcel.writeString(email)
        parcel.writeString(firstname)
        parcel.writeString(lastname)
    }

    override fun describeContents(): Int {
        return 0
    }

    companion object CREATOR : Parcelable.Creator<User> {
        override fun createFromParcel(parcel: Parcel): User {
            return User(parcel)
        }

        override fun newArray(size: Int): Array<User?> {
            return arrayOfNulls(size)
        }
    }
}